# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
  - 1.0.5
  - 1.3.0

# Allow the nightly build to fail
matrix:
  allow_failures:
    - julia: nightly
